ersion: "3.8"

services:
  db:
    image: mysql:latest
    container_name: KSS_DB_container #수정 가능
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kss1234 #수정 가능
      MYSQL_DATABASE: user_db #
      MYSQL_USER: admin #
      MYSQL_PASSWORD: kss1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql


    web:
      image: php:8.1-apache # PHP와 Apache가 포함된 이미지
      container_name: KSS_WEB_container # 웹 서버 컨테이너 이름
      restart: always
      ports:
            - "8080:80" # 로컬 포트 8080 -> 컨테이너의 80번 포트
      volumes:
        - ../src:/var/www/html       # PHP 소스 파일 경로
        - ../static:/var/www/html/static # 정적 파일 경로
        - ../templates:/var/www/html/templates # 템플릿 경로
      environment:
        - APACHE_DOCUMENT_ROOT=/var/www/html # Apache 문서 루트 설정
      depends_on:
        - db # DB 컨테이너가 먼저 시작되도록 설정

volumes:
  db_data: