version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: KSS_DB_container #수정 가능
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kss1234 #수정 가능
      MYSQL_DATABASE: user_db #
      MYSQL_USER: admin #
      MYSQL_PASSWORD: kss1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
